name: Auto update README.md
permissions:
  contents: write
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - README.md

jobs:
  update_read_me:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: list_folder_and_note_to_tmp
        run: |
          ls -1d */ | sed 's#/##' > tmp.txt
      - name: update README.md
        run: |
          echo "# Hello everyone!ðŸ‘‹" > README.md
          echo "This is my repository for Leetcode Daily.ðŸ’ªðŸ’ª" >> README.md
          echo "My Leetcode: [SChierk](https://leetcode.com/u/SChierk/)" >> README.md
          echo "" >> README.md
          echo "## You can see the list of topics I've already solved below" >> README.md
          cat tmp.txt >> README.md
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README.md"
          git push